### ISSUE TITLE
Inital set up

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/penprojprsctice#1]
As a **dev** I can **set up the initial project structure** so that **I can get started!**

# Acceptance Criteria

 - Basic project structure set up for a MERN app

# Tasks

- [ ] initialise node,js project
```
npm init -y    
```

- [ ] install Next.js
```
npx create-next-app@latest .
```

- [ ] Remove unwanted boilerplate

- [ ] Install required packages
```
npm i mongoose dotenv cors helmet express nodemon http-errors morgan
```

- [ ] Add components dir

- [ ] Add daisyui

```
npm i -D daisyui@latest
```
add below to tailwind.config.js
```
module.exports = {
  plugins: [require("daisyui")],
}
```

- [ ] Add index.js to root

- [ ] add below to "scripts" in package.json
```
"start": "nodemon index.js",
```

- [ ] Import required libraries etc in index.js
```
const express = require('express');
const app = express();
const mongoose = require('mongoose');
const morgan = require('morgan');
const helmet = require('helmet');
const cors = require('cors');
require('dotenv').config();
const createError = require('http-errors');
const { User } = require('./models/user');
const { v4: uuidv4 } = require('uuid');

const port = 3001;
```

- [ ] tell app to use those libraries
```
app.use(express.json());
app.use(morgan);
app.use(helmet());

app.use(
  cors({
    origin: 'http://localhost:3000',
  })
);
```

- [ ] Set up server
```
app.listen(port, () => {
  console.log(`Server is running on port ${port}`);
});
```

- [ ] Set up Mongodb

- [ ] Create .env and add mongo connection uri
